import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import {
  handleNewAircraft,
  handleDeleteAircraft,
  handleEditAircraft,
  handleListAircraft
} from '../services/crud_aircrafts'

import {
  handleNewPlayer,
  handleEditPlayer,
  handleDeletePlayer,
  handleListPlayer,
  handleGetPlayer
} from '../services/crud_players'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={handleNewAircraft}>create aircraft</button>
        <button onClick={handleEditAircraft}>edit aircraft</button>
        <button onClick={handleDeleteAircraft}>delete aircraft</button>
        <button onClick={handleListAircraft}>list aircraft</button>
        
        <br/>

        <button onClick={handleNewPlayer}>create player</button>
        <button onClick={handleEditPlayer}>edit player</button>
        <button onClick={handleDeletePlayer}>delete player</button>
        <button onClick={handleListPlayer}>list player</button>
        <button onClick={handleGetPlayer}>get player</button>
        
      </main>

      <footer className={styles.footer}>
        footer
      </footer>
    </div>
  )
}

export default Home
